### ISSUE TITLE
smart connection for android native

### ISSUE THREAD

**Issue by dimasoktanugraha** [CassieLuoli/react-native-smartconnection#1]
great project. is that possible to make smatconnection for mediatek with android native? i had read the library which contain c file and .a file. so, i confused how to integrated that file in android studio. con you give me any advice? thank you very much

**Comment by Tony---Zhang** [comment]
This project was available for both Android & iOS.
We got so files(libraries) from mediatek demo. Then we just put those so files to jniLibs as Android import c files common way. After that we capsulated this feature to SmartConfigHelper.java. Finally we added react native module to made our smart connect works well.

**Comment by dimasoktanugraha** [comment]
i still confused how to integrate c file / ndk on android studio. is there any example project in android native?

**Comment by dimasoktanugraha** [comment]
i'm already put .so file in jnilibs , capsulated to jniLoader.java and success to load it on MainActivity.java. but i got error "No implementation found" like this
java.lang.UnsatisfiedLinkError: No implementation found for int ai.widya.mediatekso.JniLoader.GetLibVersion()
And i dont know how to add react native module on android studio.
i really need your help.

**Comment by Tony---Zhang** [comment]
1. So file load

We usually use the following method to load so file, then we can call `jniLoader.GetLibVersion()` method when everything is OK.
```
System.loadLibrary(so_file_name)
```
[Reference](https://developer.android.com/reference/java/lang/System.html#loadLibrary(java.lang.String))

For the exception `java.lang.UnsatisfiedLinkError`:
```
if either the libname argument contains a file path, the native library is not statically linked with the VM, or the library cannot be mapped to a native library image by the host system.
```

2. React Native: native module
[Refrence](https://facebook.github.io/react-native/docs/native-modules-android)
